###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: installer
  name: installer
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: installer
  template:
    metadata:
      labels:
        cluster: management
        component: installer
    spec:
      containers:
      - name: installer
        image: __NPH_REGISTRY_NAMESPACE/installer:__NPH_VERSION
        imagePullPolicy: Always
        volumeMounts:
        - name: installer-config
          mountPath: "/nalej/assets/appcluster"
          readOnly: true
        - name: temp-dir
          mountPath: "/tmp/nalej"
        - name: ca-certificate-volume
          mountPath: "/nalej/cacert"
        - name: tls-client-certificate-volume
          mountPath: "/nalej/clientcert"
        env:
        - name: MNGT_PUBLIC_HOST
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: public_host
        - name: MNGT_PUBLIC_PORT
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: public_port
        - name: DNS_PUBLIC_HOST
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: dns_host
        - name: DNS_PUBLIC_PORT
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: dns_port
        - name: TARGET_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: environment
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: authx-secret
              key: secret
        args:
          - "run"
          - "--managementClusterPublicHost=$(MNGT_PUBLIC_HOST)"
          - "--managementClusterPublicPort=$(MNGT_PUBLIC_PORT)"
          - "--dnsClusterPublicHost=$(DNS_PUBLIC_HOST)"
          - "--dnsClusterPublicPort=$(DNS_PUBLIC_PORT)"
          - "--componentsPath=/nalej/assets/"
          - "--binaryPath=/nalej/bin/"
          - "--tempPath=/tmp/nalej/"
          - "--targetEnvironment=$(TARGET_ENVIRONMENT)"
          - "--authSecret=$(AUTH_SECRET)"
          - "--clusterCertIssuerCACertPath=/nalej/cacert/ca.crt"
          - "--netMode=istio"
          - "--istioPath=/istio"
        securityContext:
          runAsUser: 2000
      volumes:
      - name: installer-config
        configMap:
          name: installer-config
      - name: temp-dir
        emptyDir: {}
      - name: ca-certificate-volume
        secret:
          secretName: ca-certificate
      - name: tls-client-certificate-volume
        secret:
          secretName: tls-client-certificate
