###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: installer
  name: installer
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: installer
  template:
    metadata:
      labels:
        cluster: management
        component: installer
    spec:
      containers:
      - name: installer
        image: nalej/installer:VERSION
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: installer-config
          mountPath: "/nalej/assets/appcluster"
          readOnly: true
        - name: temp-dir
          mountPath: "/tmp/nalej"
        args:
          - "run"
          - "--debug"
          - "--componentsPath=/nalej/assets/"
          - "--binaryPath=/nalej/bin/"
          - "--tempPath=/tmp/nalej/"
        securityContext:
          runAsUser: 2000
      volumes:
      - name: installer-config
        configMap:
          name: installer-config
      - name: temp-dir
        emptyDir: {}
      imagePullSecrets:
      - name: myregistrykey
