###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: installer
  name: installer
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: installer
  template:
    metadata:
      labels:
        cluster: management
        component: installer
    spec:
      containers:
      - name: installer
        image: nalej/installer:VERSION
        imagePullPolicy: Always
        args:
          - "run"
          - "--debug"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: myregistrykey
