###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: installer
  name: installer
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: installer
  template:
    metadata:
      labels:
        cluster: management
        component: installer
    spec:
      containers:
      - name: installer
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/installer:__NPH_VERSION
        imagePullPolicy: Always
        volumeMounts:
        - name: installer-config
          mountPath: "/nalej/assets/appcluster"
          readOnly: true
        - name: temp-dir
          mountPath: "/tmp/nalej"
        - name: zt-planet-secret-volume
          mountPath: "/nalej/zt"
        - name: tls-ca-certificate-volume
          mountPath: "/nalej/cacert"
        env:
        - name: MNGT_PUBLIC_HOST
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: public_host
        - name: MNGT_PUBLIC_PORT
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: public_port
        - name: DNS_PUBLIC_HOST
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: dns_host
        - name: DNS_PUBLIC_PORT
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: dns_port
        - name: TARGET_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: environment
        - name: PROD_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-registry
              optional: true
              key: username
        - name: PROD_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-registry
              optional: true
              key: password
        - name: PROD_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-registry
              optional: true
              key: url
        - name: STAGING_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-staging-registry
              optional: true
              key: username
        - name: STAGING_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-staging-registry
              optional: true
              key: password
        - name: STAGING_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-staging-registry
              optional: true
              key: url
        - name: DEV_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-dev-registry
              optional: true
              key: username
        - name: DEV_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-dev-registry
              optional: true
              key: password
        - name: DEV_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-dev-registry
              optional: true
              key: url
        - name: PUBLIC_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-public-registry
              optional: true
              key: username
        - name: PUBLIC_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-public-registry
              optional: true
              key: password
        - name: PUBLIC_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              name: credentials-nalej-public-registry
              optional: true
              key: url
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: authx-secret
              key: secret
        args:
          - "run"
          - "--debug"
          - "--managementClusterPublicHost=$(MNGT_PUBLIC_HOST)"
          - "--managementClusterPublicPort=$(MNGT_PUBLIC_PORT)"
          - "--dnsClusterPublicHost=$(DNS_PUBLIC_HOST)"
          - "--dnsClusterPublicPort=$(DNS_PUBLIC_PORT)"
          - "--componentsPath=/nalej/assets/"
          - "--binaryPath=/nalej/bin/"
          - "--tempPath=/tmp/nalej/"
          - "--targetEnvironment=$(TARGET_ENVIRONMENT)"
          - "--ztPlanetSecretPath=/nalej/zt/planet"
          - "--authSecret=$(AUTH_SECRET)"
          - "--clusterCertIssuerCACertPath=/nalej/cacert/"
        securityContext:
          runAsUser: 2000
      volumes:
      - name: installer-config
        configMap:
          name: installer-config
      - name: temp-dir
        emptyDir: {}
      - name: zt-planet-secret-volume
        secret:
          secretName: zt-planet
      - name: tls-ca-certificate-volume
        secret:
          secretName: tls-ca-certificate
      imagePullSecrets:
      - name: nalej-registry
