apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    security:
      selfSigned: false
    gateways:
      istio-ingressgateway:
        env:
          ISTIO_META_NETWORK: "master"
    global:
      mtls:
        enabled: true
      controlPlaneSecurityEnabled: true
      proxy:
        accessLogFile: "/dev/stdout"
      network: master
      meshExpansion:
        enabled: true
    pilot:
      meshNetworks:
        networks:
          master:
            endpoints:
              - fromRegistry: Kubernetes
            gateways:
              - address: 0.0.0.0
                port: 443
